---

#
# Todo: break this out into multiple roles per sensor / packages / pi setup
#
#

- name: Install required packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - build-essential
    - python-dev
    - python-openssl
    - python-smbus
    - i2c-tools
    - bc
    - curl
  become: true

- name: configure /boot/config.txt and /etc/modules
  lineinfile :
    dest: "{{ item.dest }}" 
    line: "{{ item.line }}"
    insertafter: "{{ item.insertafter }}"
    state: "{{ item.state }}"
    backup: no
  with_items:
          - { dest: '/boot/firmware/config.txt', line: "dtoverlay=w1-gpio", insertafter: 'EOF', state: 'present' }
          - { dest: '/boot/firmware/config.txt', line: "dtparam=i2c1=on", insertafter: 'EOF', state: 'present' }
          - { dest: '/boot/firmware/config.txt', line: "dtparam=i2c_arm=on", insertafter: 'EOF', state: 'present' }
          - { dest: '/etc/modules', line: "i2c-bcm2708", insertafter: 'EOF', state: 'present' }
          - { dest: '/etc/modules', line: "i2c-dev", insertafter: 'EOF', state: 'present' }
  become: true

- name: create directory for scripts
  file:
    path: "{{ install_path }}"
    state: directory

- name: git clone https://github.com/adafruit/Adafruit_Python_DHT.git
  git:
    repo: 'https://github.com/adafruit/Adafruit_Python_DHT.git'
    dest: "{{ install_path }}Adafruit_Python_DHT/"
    force: true

- name: sudo python setup.py install for DHT
  shell: "/usr/bin/python {{ install_path }}Adafruit_Python_DHT/setup.py install"
  args:
    chdir: "{{ install_path }}Adafruit_Python_DHT/"
  become: true

- name: git clone https://github.com/adafruit/Adafruit_Python_BMP.git 
  git:
    repo: 'https://github.com/adafruit/Adafruit_Python_BMP.git'
    dest: "{{ install_path }}Adafruit_Python_BMP/"
    force: true

- name: sudo python setup.py install for BMP
  shell: "/usr/bin/python {{ install_path }}Adafruit_Python_BMP/setup.py install"
  args:
    chdir: "{{ install_path }}Adafruit_Python_BMP/"
  become: true

- name: change permissions on BMP sample script
  file:
    path: "{{ install_path }}Adafruit_Python_BMP/examples/simpletest.py"
    mode: 0744

- name: copy range finder script from template
  # Range finder script credits belong to https://www.modmypi.com/blog/hc-sr04-ultrasonic-range-sensor-on-the-raspberry-pi
  template:
    src: "{{ item.src }}" 
    dest: "{{ install_path }}{{ item.dest }}"
    mode: 0744
    owner: ubuntu
    group: ubuntu
  with_items:
    - { src: 'range_sensor.py.j2', dest: 'range_sensor.py' }
    - { src: 'pi_dock.sh.j2', dest: 'pi_dock.sh' }

#- name: configure cron job
#  cron:
#    name: "poll sensor data"
#    minute: "*/1"
#    state: present
#    job: "{{ install_path }}pi_dock.sh >/dev/null 2>&1"

  # this is a ansible 2.2 feature
  #- name: enable cron daemon in systemd
  #systemd:
  #  name: cron
  #  enabled: yes
  #  state: started
  #become: true

#- name: enable systemd cron the old way
#  shell: systemctl enable cron
#  become: true
